development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: music
  username: root
  password: '123'
  socket: /var/run/mysqld/mysqld.sock

test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: smusic_test
  username: root
  password: '123'

production:
  adapter: mysql2
  encoding: utf8
  database: standee_prod
  username: root
  password: ''

cucumber:
  <<: *test
